name: Deploy on GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
jobs:
  build-and-deploy:
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://docs.dodona.be/papyros/
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
      - name: Remove deploy label
        uses: buildsville/add-remove-label@v1
        with:
          label: deploy
          type: remove
