name: Lint

on:
  push:

jobs:
  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: yarn
    - name: Install dependencies
      run: |
        yarn install
    - name: Lint
      run: |
        yarn lint
