name: Release as NPM package
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://docs.dodona.be/papyros/
    steps:
      - name: Parse tag
        id: parse_tag
        run: "echo ${{ github.ref }} | sed 's#^refs/tags/#::set-output name=version::#'"

