name: Publish on NPM

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://docs.dodona.be/papyros/
    steps:
      - name: Parse tag
        id: parse_tag
        run: "echo ${{ github.ref }} | sed 's#^refs/tags/#::set-output name=version::#'"
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build
      - name: Publish @dodona/papyros to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          check-version: true
          access: public
