name: Validate translations

on:
  push:
  workflow_dispatch:

jobs:
  validate_translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: yarn
    - name: Install dependencies
      run: |
        yarn install
    - name: Check translations
      run: |
          yarn run validate:translations
    - name: Add annotations
      uses: pytorch/add-annotations-github-action@master
      with:
        check_name: Check translations
        linter_output_path: translationIssues.txt
        commit_sha: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
