name: Validate translations

on:
  push:
  workflow_dispatch:

jobs:
  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: yarn
    - name: Install dependencies
      run: |
        yarn install
    - name: Check translations
    - run: |
          yarn run validate:translations
     - uses: pytorch/add-annotations-github-action@master
       with:
         check_name: Check translations
         linter_output_path: translationIssues.txt
         commit_sha: ${{ github.event.pull_request.head.sha }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
